from __future__ import annotations

import io
import re
from datetime import datetime

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

BRAND_BLUE = RGBColor(31, 78, 121)
DARK_TEXT = RGBColor(31, 41, 55)
GRAY_TEXT = RGBColor(75, 85, 99)
LIGHT_BLUE_HEX = "DCE6F2"
BORDER_HEX = "D1D5DB"


def _safe_text(value: object) -> str:
    if value is None:
        return ""
    return str(value).replace("\x00", "").strip()


def _slugify(value: str) -> str:
    value = _safe_text(value).lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "document"


def _set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), fill)
    tc_pr.append(shd)


def _set_cell_border(cell, color: str = BORDER_HEX) -> None:
    tc = cell._tc
    tc_pr = tc.get_or_add_tcPr()
    tc_borders = tc_pr.first_child_found_in("w:tcBorders")
    if tc_borders is None:
        tc_borders = OxmlElement("w:tcBorders")
        tc_pr.append(tc_borders)
    for edge in ("top", "left", "bottom", "right"):
        tag = f"w:{edge}"
        element = tc_borders.find(qn(tag))
        if element is None:
            element = OxmlElement(tag)
            tc_borders.append(element)
        element.set(qn("w:val"), "single")
        element.set(qn("w:sz"), "4")
        element.set(qn("w:space"), "0")
        element.set(qn("w:color"), color)


def _style_document(doc: Document) -> None:
    section = doc.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    styles = doc.styles
    normal = styles["Normal"]
    normal.font.name = "Arial"
    normal.font.size = Pt(10.5)
    normal.font.color.rgb = DARK_TEXT

    for style_name, size, color in [
        ("Heading 1", 18, BRAND_BLUE),
        ("Heading 2", 14, BRAND_BLUE),
        ("Heading 3", 12, BRAND_BLUE),
    ]:
        style = styles[style_name]
        style.font.name = "Arial"
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = color


def _add_cover(doc: Document, title: str, doc_type: str, prepared_by: str, subtitle: str) -> None:
    table = doc.add_table(rows=1, cols=1)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    cell = table.cell(0, 0)
    _set_cell_shading(cell, "1F4E79")
    _set_cell_border(cell, "1F4E79")
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER

    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(20)
    run.font.name = "Arial"
    run.font.color.rgb = RGBColor(255, 255, 255)

    for line in [doc_type, subtitle, f"Prepared by: {prepared_by or 'VectorOps'}", datetime.now().strftime("%B %d, %Y")]:
        if not line:
            continue
        para = cell.add_paragraph()
        para.alignment = WD_ALIGN_PARAGRAPH.LEFT
        r = para.add_run(line)
        r.font.name = "Arial"
        r.font.size = Pt(10.5)
        r.font.color.rgb = RGBColor(225, 229, 234)

    doc.add_paragraph()


def _add_footer(doc: Document, prepared_by: str) -> None:
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(f"Generated by VectorOps Mission Impact Copilot · {prepared_by or 'VectorOps'} · {datetime.now().strftime('%Y-%m-%d')}")
    run.font.name = "Arial"
    run.font.size = Pt(8)
    run.font.color.rgb = GRAY_TEXT


def _is_markdown_table(lines: list[str], index: int) -> bool:
    if index + 1 >= len(lines):
        return False
    return "|" in lines[index] and re.match(r"^\s*\|?\s*[-:]+", lines[index + 1]) is not None


def _parse_table(lines: list[str], start: int) -> tuple[list[list[str]], int]:
    rows: list[list[str]] = []
    i = start
    while i < len(lines) and "|" in lines[i].strip():
        line = lines[i].strip().strip("|")
        # skip Markdown separator row
        if re.match(r"^\s*[-:|\s]+$", line):
            i += 1
            continue
        rows.append([c.strip() for c in line.split("|")])
        i += 1
    return rows, i


def _add_table(doc: Document, rows: list[list[str]]) -> None:
    if not rows:
        return
    col_count = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=col_count)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"

    for r_idx, row in enumerate(rows):
        for c_idx in range(col_count):
            cell = table.cell(r_idx, c_idx)
            cell.text = row[c_idx] if c_idx < len(row) else ""
            _set_cell_border(cell)
            if r_idx == 0:
                _set_cell_shading(cell, LIGHT_BLUE_HEX)
                for p in cell.paragraphs:
                    for run in p.runs:
                        run.bold = True
                        run.font.color.rgb = BRAND_BLUE
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.name = "Arial"
                    run.font.size = Pt(9)
    doc.add_paragraph()


def _add_markdown_content(doc: Document, content: str) -> None:
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        if _is_markdown_table(lines, i):
            rows, next_i = _parse_table(lines, i)
            _add_table(doc, rows)
            i = next_i
            continue

        if stripped.startswith("### "):
            doc.add_heading(stripped[4:].strip(), level=3)
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:].strip(), level=2)
        elif stripped.startswith("# "):
            doc.add_heading(stripped[2:].strip(), level=1)
        elif stripped.startswith(("- ", "* ")):
            doc.add_paragraph(stripped[2:].strip(), style="List Bullet")
        elif re.match(r"^\d+\.\s+", stripped):
            doc.add_paragraph(re.sub(r"^\d+\.\s+", "", stripped), style="List Number")
        else:
            para = doc.add_paragraph()
            # Lightweight bold support for **text**
            parts = re.split(r"(\*\*[^*]+\*\*)", stripped)
            for part in parts:
                if part.startswith("**") and part.endswith("**"):
                    run = para.add_run(part[2:-2])
                    run.bold = True
                else:
                    para.add_run(part)
        i += 1


def create_docx(
    *,
    title: str,
    content: str,
    doc_type: str = "PM Report",
    prepared_by: str = "VectorOps",
    subtitle: str = "AI-generated draft for human review",
) -> bytes:
    """Create a polished Word document from markdown-like AI output."""
    doc = Document()
    _style_document(doc)
    _add_cover(doc, _safe_text(title) or "PM Report", _safe_text(doc_type) or "PM Report", _safe_text(prepared_by), _safe_text(subtitle))
    _add_markdown_content(doc, content)
    _add_footer(doc, prepared_by)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def build_docx_filename(title: str, doc_type: str = "pm-report") -> str:
    date_stamp = datetime.now().strftime("%Y%m%d")
    return f"{_slugify(doc_type)}-{_slugify(title)}-{date_stamp}.docx"
